// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NRIClient is the client API for NRI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NRIClient interface {
	Check(ctx context.Context, in *ServiceRequest, opts ...grpc.CallOption) (*ServiceResponse, error)
}

type nRIClient struct {
	cc grpc.ClientConnInterface
}

func NewNRIClient(cc grpc.ClientConnInterface) NRIClient {
	return &nRIClient{cc}
}

func (c *nRIClient) Check(ctx context.Context, in *ServiceRequest, opts ...grpc.CallOption) (*ServiceResponse, error) {
	out := new(ServiceResponse)
	err := c.cc.Invoke(ctx, "/main.NRI/Check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NRIServer is the server API for NRI service.
// All implementations must embed UnimplementedNRIServer
// for forward compatibility
type NRIServer interface {
	Check(context.Context, *ServiceRequest) (*ServiceResponse, error)
	mustEmbedUnimplementedNRIServer()
}

// UnimplementedNRIServer must be embedded to have forward compatible implementations.
type UnimplementedNRIServer struct {
}

func (UnimplementedNRIServer) Check(context.Context, *ServiceRequest) (*ServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedNRIServer) mustEmbedUnimplementedNRIServer() {}

// UnsafeNRIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NRIServer will
// result in compilation errors.
type UnsafeNRIServer interface {
	mustEmbedUnimplementedNRIServer()
}

func RegisterNRIServer(s grpc.ServiceRegistrar, srv NRIServer) {
	s.RegisterService(&NRI_ServiceDesc, srv)
}

func _NRI_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NRIServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.NRI/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NRIServer).Check(ctx, req.(*ServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NRI_ServiceDesc is the grpc.ServiceDesc for NRI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NRI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "main.NRI",
	HandlerType: (*NRIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _NRI_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
